### PR TITLE
Require Directive.isRepeatable on introspection

### LINKED ISSUE #11: Directive.isRepeatable is not present
**Describe the bug**

`Introspector` calls `BuildClientSchema::build()` which requires directive to contain `isRepeatable` info

```php
        return new Directive([
            'name' => $directive['name'],
            'description' => $directive['description'],
            'args' => $this->buildInputValueDefMap($directive['args']),
            'isRepeatable' => $directive['isRepeatable'],
            'locations' => $directive['locations'],
        ]);
```

graphql-php v14.5.1

### PR DESCRIPTION
**Pull request by simPod**
- [ ] Added automated tests
- [ ] Documented for all relevant versions
- [ ] Updated the changelog

Resolves #11

**Changes**

Require Directive.isRepeatable on introspection. graphql-php BuildClientSchema requires it to construct Directive

**Breaking changes**

🤷🏾

### CODE REVIEW

File: src/Introspector.php [hunk 1]
```diff
@@ -24,7 +24,7 @@ public function introspect(): void
     {
         $client = $this->endpointConfig->client();
 
-        $introspectionResult = $client->request(Introspection::getIntrospectionQuery());
+        $introspectionResult = $client->request(Introspection::getIntrospectionQuery(['directiveIsRepeatable' => true]));
```
Comment (spawnia) [inline src/Introspector.php:27]:
```suggestion
        $introspectionResult = $client->request(
            Introspection::getIntrospectionQuery([
                'directiveIsRepeatable' => true,
            ])
        );
```

**Comment by spawnia** [comment]
Thanks @simPod, great to see you getting involved.

**Comment by KorvinSzanto** [comment]
This change leads to `Cannot query field "isRepeatable" on type "__Directive".` for my setup.

**Comment by simPod** [comment]
@KorvinSzanto can you somehow reproduce/add test or sth + provide details? That might help, thx!

**Comment by spawnia** [comment]
> This change leads to `Cannot query field "isRepeatable" on type "__Directive".` for my setup.

`repeatable` directives are a relatively new addition to the GraphQL specification. The server you are trying to query does not support them yet, so it naturally does not know the related introspection field.

**Comment by KorvinSzanto** [comment]
@spawnia @simPod I'm using apiplatform for my graphql server.

**Comment by simPod** [comment]
@spawnia any idea how we could make it BC? This either works on new or old specs but not both.
